pub(crate) fn launcher_commands() -> Vec<(&'static str, &'static str)> {
    vec![
        ("Host Quick (127.0.0.1)", "h.quick 127.0.0.1"),
        ("Host TCP 22,80,443", "h.tcp 127.0.0.1 22,80,443"),
        ("Host UDP 53,161", "h.udp 127.0.0.1 53,161"),
        ("Host SYN 22,80,443", "h.syn 127.0.0.1 22,80,443"),
        ("Host ARP 192.168.1.0/24", "h.arp 192.168.1.0/24"),
        (
            "Web Dir example.com",
            "w.dir https://example.com /,/robots.txt",
        ),
        (
            "Web Fuzz example.com/FUZZ",
            "w.fuzz https://example.com/FUZZ admin,login",
        ),
        ("Web DNS example.com", "w.dns example.com www,api,dev"),
        ("Web Crawl example.com", "w.crawl https://example.com --max-depth 2"),
        ("Web Live batch", "w.live https://example.com,https://example.org"),
        ("Vuln Lint builtin templates", "v.lint ./nuclei-templates"),
        ("Vuln Scan example.com", "v.scan https://example.com"),
        ("Vuln Container Audit", "v.ca ./k8s"),
        ("Vuln System Guard", "v.sg"),
        ("Vuln Stealth Check", "v.sc https://example.com"),
        ("Vuln Fragment Audit", "v.fa https://example.com"),
        ("Reverse Analyze /bin/ls", "r.analyze /bin/ls"),
        ("Reverse Plan /bin/ls", "r.plan /bin/ls objdump"),
        ("Reverse Run /bin/ls", "r.run /bin/ls ghidra full"),
        ("Reverse Jobs", "r.jobs"),
        ("Reverse Job Status", "r.status <job_id>"),
        ("Reverse Job Logs", "r.logs <job_id> --stream both"),
        ("Reverse Job Artifacts", "r.artifacts <job_id>"),
        ("Reverse Job Functions", "r.funcs <job_id>"),
        ("Reverse Job Show", "r.show <job_id> main"),
        ("Reverse Job Search", "r.search <job_id> crypto"),
        ("Reverse Job Clear", "r.clear <job_id>"),
        ("Reverse Job Prune", "r.prune --keep 20"),
        ("Reverse Job Doctor", "r.doctor <job_id>"),
        ("Reverse Debug Script", "r.debug /bin/ls /tmp/ls.gdb pwndbg"),
        ("Focus Reverse Tab", "zfocus reverse"),
    ]
}

pub(crate) fn completion_heads() -> &'static [&'static str] {
    &[
        "h.quick",
        "h.tcp",
        "h.udp",
        "h.syn",
        "h.arp",
        "w.dir",
        "w.fuzz",
        "w.dns",
        "w.crawl",
        "w.live",
        "v.lint",
        "v.scan",
        "v.ca",
        "v.sg",
        "v.sc",
        "v.fa",
        "r.analyze",
        "r.plan",
        "r.run",
        "r.jobs",
        "r.status",
        "r.logs",
        "r.artifacts",
        "r.funcs",
        "r.show",
        "r.search",
        "r.clear",
        "r.prune",
        "r.doctor",
        "r.debug",
        "zrun",
        "zlogs",
        "zshell",
        "zart",
        "zrev",
        "zfocus",
        "host",
        "web",
        "vuln",
        "reverse",
    ]
}
