mod app_state;
mod command_build;
mod command_catalog;
mod command_exec;
mod input;
mod models;
pub(crate) mod native_hubs;
mod normal_global;
mod normal_panes;
mod pane_cache_text;
mod pane_text;
mod perf;
mod project_store;
mod render;
pub(crate) mod reverse_deck;
mod reverse_native_runtime;
pub(crate) mod reverse_picker;
pub(crate) mod reverse_surface;
pub(crate) mod reverse_workbench;
mod reverse_workbench_support;
mod script_runtime;
mod task_actions;
mod task_store;
mod terminal;
mod view;
mod zellij;
mod zellij_layout;
mod zellij_query;
mod zellij_registry;

pub mod app;
