use super::AppState;
use crate::tui::render::RenderCtx;

impl AppState {
    pub(crate) fn render_ctx<'a>(&'a self, footer_text: &'a str) -> RenderCtx<'a> {
        RenderCtx {
            pane: self.pane,
            main_layout: self.main_layout,
            filter: self.filter,
            task_tab: self.task_tab,
            result_kind_filter: self.result_kind_filter,
            result_failed_first: self.result_failed_first,
            input_mode: self.input_mode,
            current_project: &self.current_project,
            script_running: self.script_running,
            all_tasks: &self.all_tasks,
            tasks: &self.tasks,
            task_selected: self.task_selected,
            detail_scroll: self.detail_scroll,
            task_detail_lines: &self.task_detail_lines,
            task_table_rows: &self.task_table_rows,
            task_compact_items: &self.task_compact_items,
            launcher_items: &self.launcher_items,
            launcher_selected: self.launcher_selected,
            launcher_list_items: &self.launcher_list_items,
            launcher_detail_lines: &self.launcher_detail_lines,
            scripts: &self.scripts,
            script_selected: self.script_selected,
            script_buffer: &self.script_buffer,
            script_dirty: self.script_dirty,
            script_file_items: &self.script_file_items,
            script_output_lines: &self.script_output_lines,
            result_indices: &self.result_indices,
            result_selected: self.result_selected,
            effect_scroll: self.effect_scroll,
            result_detail_lines: &self.result_detail_lines,
            result_list_items: &self.result_list_items,
            projects: &self.projects,
            project_selected: self.project_selected,
            dashboard_lines: &self.dashboard_lines,
            project_list_items: &self.project_list_items,
            project_detail_lines: &self.project_detail_lines,
            footer_text,
            zellij_managed: crate::tui::zellij::is_managed_runtime(),
            zellij_session: crate::tui::zellij::session_name(),
            mini_console_visible: self.mini_console_visible,
            mini_console_layout: self.mini_console_layout,
            mini_float_x_pct: self.mini_float_x_pct,
            mini_float_y_pct: self.mini_float_y_pct,
            mini_float_w_pct: self.mini_float_w_pct,
            mini_float_h_pct: self.mini_float_h_pct,
            mini_popup_mode: self.mini_popup_mode,
            mini_console_tab: self.mini_console_tab,
            mini_console_scroll: self.mini_console_scroll,
            mini_console_lines: &self.mini_console_lines,
            perf_cpu_pct: self.perf_cpu_pct,
            perf_mem_used_mb: self.perf_mem_used_mb,
            perf_mem_total_mb: self.perf_mem_total_mb,
            perf_proc_rss_mb: self.perf_proc_rss_mb,
            perf_loadavg: &self.perf_loadavg,
            ui_tick: self.ui_tick,
        }
    }
}
